### ISSUE TITLE
Implement Entity models into infrastructure project ==> Product microservice

### ISSUE THREAD

**Issue by AphonsusSmertz** [LesterCerioli/StockControl#15]
It's necessary provides a microservice for Products where it's necessary to register products assigned to categories.

This microservice will have your database and API.

**Comment by LesterCerioli** [comment]
I assigned this issue for you, @AphonsusSmertz

**Comment by AphonsusSmertz** [comment]
Very thanks @LesterCerioli

**Comment by AphonsusSmertz** [comment]
### Implement Entity models into Infrastructure project
